version: '3.5'

services:
    nginx:
        build:
            context: .
            dockerfile: ./${APP_ENV}/nginx/Dockerfile
        environment:
            - VIRTUAL_HOST=${HTTP_HOST}
        volumes:
            - ../public:/var/www/html/public
            - ./${APP_ENV}/nginx/config/vhost.nginx:/etc/nginx/conf.d/default.conf:ro
        restart: unless-stopped

    php:
        build:
            context: .
            dockerfile: ./${APP_ENV}/php/Dockerfile
            args:
                UID: "${DOCKER_UID}"
                TZ: "${TZ}"
        env_file:
            - .env
        volumes:
            - ..:/var/www/html
        restart: unless-stopped

    mysql:
        image: mysql:8
        env_file:
            - .env
        volumes:
            - mysql:/var/lib/mysql
        restart: unless-stopped

volumes:
    mysql:
